// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearWallpaper() {
  return window['go']['main']['App']['ClearWallpaper']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetHostInfo() {
  return window['go']['main']['App']['GetHostInfo']();
}

export function GetWallpaperData() {
  return window['go']['main']['App']['GetWallpaperData']();
}

export function SelectWallpaper() {
  return window['go']['main']['App']['SelectWallpaper']();
}

export function SetBgMode(arg1) {
  return window['go']['main']['App']['SetBgMode'](arg1);
}

export function SetBlur(arg1) {
  return window['go']['main']['App']['SetBlur'](arg1);
}

export function SetCloseAction(arg1) {
  return window['go']['main']['App']['SetCloseAction'](arg1);
}

export function SetGlass3D(arg1) {
  return window['go']['main']['App']['SetGlass3D'](arg1);
}

export function SetInterval(arg1) {
  return window['go']['main']['App']['SetInterval'](arg1);
}

export function SetMapTheme(arg1) {
  return window['go']['main']['App']['SetMapTheme'](arg1);
}

export function SetShowLogo(arg1) {
  return window['go']['main']['App']['SetShowLogo'](arg1);
}

export function SetThrottled(arg1) {
  return window['go']['main']['App']['SetThrottled'](arg1);
}

export function SetUiTheme(arg1) {
  return window['go']['main']['App']['SetUiTheme'](arg1);
}

export function SetUnits(arg1, arg2) {
  return window['go']['main']['App']['SetUnits'](arg1, arg2);
}
