// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {store} from '../models';
import {collector} from '../models';

export function GetConfig():Promise<config.Config>;

export function GetHistory():Promise<Array<store.Point>>;

export function GetHostInfo():Promise<collector.HostInfo>;

export function SetInterval(arg1:number):Promise<void>;

export function SetMapTheme(arg1:string):Promise<void>;

export function SetThrottled(arg1:boolean):Promise<void>;

export function SetUiTheme(arg1:string):Promise<void>;

export function SetUnits(arg1:string,arg2:string):Promise<void>;
